export interface RegistryItem {
  slug: string
  name: string
  type: 'ui' | 'block' | 'template'
  githubUrl: string
  requires: string[]
  dependencies?: string[]
}

const GITHUB_BASE = 'https://raw.githubusercontent.com/lithosui/Lithos_UI/main/src'

export const registry: Record<string, RegistryItem> = {
  accordion: {
    slug: 'accordion',
    name: 'Accordion',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Accordion.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx', 'components/ui/icons/IconChevronUp.tsx'],
    dependencies: ['react-icons'],
  },
  alert: {
    slug: 'alert',
    name: 'Alert',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Alert.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'utils/colors.ts',
      'core/types.ts',
      'components/ui/Button.tsx',
      'components/ui/icons/IconUndo.tsx',
      'components/ui/icons/IconClose.tsx',
    ],
    dependencies: ['react-icons'],
  },
  avatar: {
    slug: 'avatar',
    name: 'Avatar',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Avatar.tsx`,
    requires: ['utils/cn.ts', 'utils/yiq.ts', 'core/useAccentColor.tsx'],
  },
  badge: {
    slug: 'badge',
    name: 'Badge',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Badge.tsx`,
    requires: ['utils/cn.ts', 'core/useAccentColor.tsx', 'utils/yiq.ts', 'utils/colors.ts', 'core/types.ts'],
  },
  breadcrumb: {
    slug: 'breadcrumb',
    name: 'Breadcrumb',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Breadcrumb.tsx`,
    requires: ['utils/cn.ts', 'components/ui/icons/IconHome.tsx', 'components/ui/icons/IconBreadcrumbSeparator.tsx'],
    dependencies: ['react-icons'],
  },
  button: {
    slug: 'button',
    name: 'Button',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Button.tsx`,
    requires: ['utils/cn.ts', 'utils/yiq.ts', 'core/types.ts'],
    dependencies: ['clsx', 'tailwind-merge'],
  },
  calendar: {
    slug: 'calendar',
    name: 'Calendar',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Calendar.ts`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/types.ts',
      'utils/date.ts',
      'components/ui/Button.tsx',
      'components/ui/Select.ts',
      'components/ui/icons/IconChevronDown.tsx',
      'components/ui/icons/IconChevronLeft.tsx',
      'components/ui/calendar/Calendar.tsx',
      'components/ui/calendar/CalendarDay.tsx',
      'components/ui/calendar/CalendarGrid.tsx',
      'components/ui/calendar/calendar.types.ts',
      'components/ui/calendar/calendar.utils.ts',
      'components/ui/calendar/useCalendarKeyboardNav.ts',
      'components/ui/calendar/useRainbowColors.ts',
    ],
    dependencies: ['react-icons'],
  },
  card: {
    slug: 'card',
    name: 'Card',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Card.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx'],
  },
  carousel: {
    slug: 'carousel',
    name: 'Carousel',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Carousel.ts`,
    requires: [
      'utils/cn.ts',
      'utils/scrollTo.ts',
      'components/ui/Button.tsx',
      'components/ui/carousel/Carousel.tsx',
      'components/ui/carousel/CarouselButton.tsx',
      'components/ui/carousel/CarouselControls.tsx',
      'components/ui/carousel/CarouselSlide.tsx',
      'components/ui/carousel/CarouselPagination.tsx',
      'components/ui/carousel/CarouselTrack.tsx',
      'components/ui/carousel/useCarousel.tsx',
      'components/ui/carousel/useCarouselDrag.ts',
      'components/ui/carousel/carousel.types.ts',
      'components/ui/icons/IconArrowLeft.tsx',
      'components/ui/icons/IconArrowRight.tsx',
      'components/ui/icons/IconArrowDown.tsx',
      'components/ui/icons/IconArrowUp.tsx',
      'components/ui/icons/IconCircle.tsx',
    ],
    dependencies: ['react-icons'],
  },
  checkbox: {
    slug: 'checkbox',
    name: 'Checkbox',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Checkbox.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/types.ts',
      'components/ui/icons/IconCheck.tsx',
      'components/ui/icons/IconMinus.tsx',
      'components/ui/icons/IconHeart.tsx',
      'components/ui/icons/IconHeartOutline.tsx',
      'components/ui/icons/IconBase.tsx',
    ],
    dependencies: ['react-icons'],
  },
  dialog: {
    slug: 'dialog',
    name: 'Dialog',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Dialog.tsx`,
    requires: [
      'components/ui/icons/IconClose.tsx',
      'components/ui/icons/IconSettings.tsx',
      'components/ui/icons/IconAlertTriangle.tsx',
      'components/ui/Button.tsx',
      'core/hooks/useFocusTrap.ts',
      'core/types.ts',
      'utils/cn.ts',
    ],
    dependencies: ['react-icons'],
  },
  command: {
    slug: 'command',
    name: 'Command',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Command.tsx`,
    requires: [
      'utils/cn.ts',
      'components/ui/Dialog.tsx',
      'components/ui/Kbd.tsx',
      'components/ui/Badge.tsx',
      'components/ui/icons/IconSearch.tsx',
      'components/ui/icons/IconClose.tsx',
    ],
    dependencies: ['react-icons'],
  },
  drawer: {
    slug: 'drawer',
    name: 'Drawer',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Drawer.ts`,
    requires: [
      'utils/cn.ts',
      'components/ui/Button.tsx',
      'components/ui/icons/IconClose.tsx',
      'components/ui/drawer/Drawer.tsx',
      'components/ui/drawer/DrawerBody.tsx',
      'components/ui/drawer/DrawerFooter.tsx',
      'components/ui/drawer/DrawerHeader.tsx',
      'components/ui/drawer/DrawerIndicator.tsx',
      'components/ui/drawer/DrawerTitle.tsx',
      'components/ui/drawer/drawer.types.ts',
      'components/ui/drawer/drawer.utils.ts',
      'components/ui/drawer/useDrawer.ts',
      'components/ui/drawer/useDrawerSwipe.ts',
      'components/ui/Popover.ts',
      'components/ui/Dialog.tsx',
      'core/hooks/useMediaQuery.ts',
    ],
    dependencies: ['@floating-ui/react', 'react-icons'],
  },
  dropdown: {
    slug: 'dropdown',
    name: 'Dropdown',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Dropdown.ts`,
    requires: [
      'utils/cn.ts',
      'components/ui/Button.tsx',
      'components/ui/Popover.ts',
      'components/ui/dropdown/Dropdown.tsx',
      'components/ui/dropdown/DropdownContent.tsx',
      'components/ui/dropdown/DropdownItem.tsx',
      'components/ui/dropdown/DropdownGroup.tsx',
      'components/ui/dropdown/DropdownSeparator.tsx',
      'components/ui/dropdown/DropdownTrigger.tsx',
      'components/ui/dropdown/DropdownSub.tsx',
      'components/ui/dropdown/useDropdown.ts',
      'components/ui/dropdown/DropdownNavigationContext.ts',
      'core/hooks/useListKeyNavigation.ts',
    ],
  },
  input: {
    slug: 'input',
    name: 'Input',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Input.tsx`,
    requires: [
      'utils/cn.ts',
      'utils/colors.ts',
      'components/ui/icons/IconSearch.tsx',
      'components/ui/icons/IconSettings.tsx',
    ],
    dependencies: ['react-icons'],
  },
  kbd: {
    slug: 'kbd',
    name: 'Kbd',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Kbd.tsx`,
    requires: ['utils/cn.ts', 'utils/yiq.ts', 'core/types.ts'],
  },
  pagination: {
    slug: 'pagination',
    name: 'Pagination',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Pagination.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx', 'components/ui/icons/IconChevronLeft.tsx'],
    dependencies: ['react-icons'],
  },
  popover: {
    slug: 'popover',
    name: 'Popover',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Popover.ts`,
    requires: [
      'utils/cn.ts',
      'components/ui/Button.tsx',
      'components/ui/popover/Popover.tsx',
      'components/ui/popover/PopoverContent.tsx',
      'components/ui/popover/PopoverTrigger.tsx',
      'components/ui/popover/PopoverClose.tsx',
      'components/ui/popover/usePopover.ts',
    ],
    dependencies: ['@floating-ui/react'],
  },
  select: {
    slug: 'select',
    name: 'Select',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Select.ts`,
    requires: [
      'utils/cn.ts',
      'utils/yiq.ts',
      'core/useAccentColor.tsx',
      'components/ui/Button.tsx',
      'components/ui/Popover.ts',
      'components/ui/popover/PopoverContent.tsx',
      'components/ui/popover/PopoverTrigger.tsx',
      'components/ui/popover/usePopover.ts',
      'components/ui/icons/IconChevronDown.tsx',
      'components/ui/select/Select.tsx',
      'components/ui/select/SelectTrigger.tsx',
      'components/ui/select/SelectContent.tsx',
      'components/ui/select/SelectItem.tsx',
      'components/ui/select/useSelect.tsx',
      'components/ui/select/select.types.ts',
      'core/hooks/useVirtualizer.ts',
      'core/hooks/useListKeyNavigation.ts',
    ],
    dependencies: ['@floating-ui/react', 'react-icons'],
  },
  skeleton: {
    slug: 'skeleton',
    name: 'Skeleton',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Skeleton.tsx`,
    requires: ['utils/cn.ts'],
  },
  spinner: {
    slug: 'spinner',
    name: 'Spinner',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Spinner.tsx`,
    requires: ['utils/cn.ts', 'core/useAccentColor.tsx', 'utils/yiq.ts'],
    dependencies: ['react-icons'],
  },
  table: {
    slug: 'table',
    name: 'Table',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Table.tsx`,
    requires: ['utils/cn.ts'],
  },
  tabs: {
    slug: 'tabs',
    name: 'Tabs',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Tabs.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx'],
  },
  toast: {
    slug: 'toast',
    name: 'Toast',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Toast.tsx`,
    requires: [
      'components/ui/icons/IconClose.tsx',
      'components/ui/Button.tsx',
      'core/hooks/useToast.ts',
      'core/types.ts',
      'utils/colors.ts',
      'utils/yiq.ts',
      'utils/cn.ts',
    ],
    dependencies: ['react-icons'],
  },
  toggle: {
    slug: 'toggle',
    name: 'Toggle',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Toggle.tsx`,
    requires: ['utils/cn.ts', 'components/ui/Button.tsx'],
  },
  tooltip: {
    slug: 'tooltip',
    name: 'Tooltip',
    type: 'ui',
    githubUrl: `${GITHUB_BASE}/components/ui/Tooltip.ts`,
    requires: [
      'utils/cn.ts',
      'components/ui/tooltip/Tooltip.tsx',
      'components/ui/tooltip/TooltipContent.tsx',
      'components/ui/tooltip/TooltipTrigger.tsx',
      'components/ui/tooltip/useTooltip.ts',
    ],
    dependencies: ['@floating-ui/react'],
  },

  // Blocks
  'faq-1': {
    slug: 'faq-1',
    name: 'Standard FAQ',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/FAQ/1.tsx`,
    requires: ['components/ui/Accordion.tsx'],
  },
  'feature-grids-1': {
    slug: 'feature-grids-1',
    name: 'Classic Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/FeatureGrid/1.tsx`,
    requires: ['components/ui/Card.tsx'],
  },
  'footer-1': {
    slug: 'footer-1',
    name: 'Multi-column Footer',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Footer/1.tsx`,
    requires: [],
  },
  'footer-2': {
    slug: 'footer-2',
    name: 'Minimal Footer',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Footer/2.tsx`,
    requires: [],
  },
  'hero-1': {
    slug: 'hero-1',
    name: 'Standard Hero',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Hero/1.tsx`,
    requires: ['components/ui/Badge.tsx', 'components/ui/Button.tsx'],
  },
  'hero-2': {
    slug: 'hero-2',
    name: 'Split Layout Hero',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Hero/2.tsx`,
    requires: ['components/ui/Badge.tsx', 'components/ui/Button.tsx', 'components/ui/Card.tsx'],
  },
  'navbar-1': {
    slug: 'navbar-1',
    name: 'Standard Navbar',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Navbar/1.tsx`,
    requires: ['components/ui/Button.tsx', 'components/ui/icons/IconMenu.tsx', 'components/ui/icons/IconClose.tsx'],
    dependencies: ['react-icons'],
  },
  'pricing-1': {
    slug: 'pricing-1',
    name: '3-Tier Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Pricing/1.tsx`,
    requires: ['components/ui/Card.tsx', 'components/ui/Button.tsx', 'utils/cn.ts'],
  },
  'testimonials-1': {
    slug: 'testimonials-1',
    name: 'Standard Grid',
    type: 'block',
    githubUrl: `${GITHUB_BASE}/components/blocks/Testimonials/1.tsx`,
    requires: ['components/ui/Card.tsx', 'components/ui/Avatar.tsx'],
  },

  // Templates
  'landing-1': {
    slug: 'landing-1',
    name: 'SaaS Standard Landing Page',
    type: 'template',
    githubUrl: `${GITHUB_BASE}/components/templates/Landing/1.tsx`,
    requires: [
      'components/blocks/Navbar/1.tsx',
      'components/blocks/Hero/1.tsx',
      'components/blocks/FeatureGrid/1.tsx',
      'components/blocks/Pricing/1.tsx',
      'components/blocks/Testimonials/1.tsx',
      'components/blocks/FAQ/1.tsx',
      'components/blocks/Footer/1.tsx',
    ],
  },
}
